apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-e08m
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-1-tenant/test-rhtap-1-app/devfile-sample-code-with-quarkus-e08m@sha256:8ff805e10552aff4657213367677f6b3fe7e029c0d02f9b88cc45dd1a32ae0d7
        name: my-java-quarkus
        resources: {}
status: {}
